### ISSUE TITLE
Theme hat hart codierte Abhängigkeit vom Plug-in "The Events Calendar" und funktioniert nicht mit anderen Termin Plugins

### ISSUE THREAD

**Issue by jbhs** [RRZE-Webteam/FAU-Einrichtungen#1351]
Betrifft Version: 2.3.22 des Themes.

In der Datei `functions/shortcodes.php` wird ohne Überprüfung die Funktion `tribe_get_events()` eingesetzt. Die Funktion ist jedoch nur vorhanden, wenn das Drittanbieter Plugin [The Events Calendar](https://wordpress.org/plugins/the-events-calendar/) installiert und aktiviert ist, der Shortcode `events_list` führt zu weiteren Überschneidungen mit anderen Veranstaltungs plugins. Es müsste eine Überprüfung stattfinden, ob das Plugin The Events Calendar, installiert und aktivier ist. 

Schneller Quickfix: Zeilen 346 bis 414 der Datei `shortcodes.php` auskommentieren. 

Hier noch die Logs dazu:

```
[2023-06-19 09:29:38.727943] [web-mcnulty-php80] [error] [php] [IP:0] PHP Fatal error: Uncaught Error: Call to undefined function tribe_get_events() in functions/shortcodes.php:353\nStack trace:\n#0 websource/wp-includes/shortcodes.php(355): events_list_shortcode(Array, '', 'events_list')\n#1 [internal function]: do_shortcode_tag(Array)\n#2 websource/wp-includes/shortcodes.php(227): preg_replace_callback('/\\\\[(\\\\[?)(events...', 'do_shortcode_ta...', '\\r\\nRund um das <...')\n#3 websource/wp-content/plugins/rrze-elements/includes/Accordion/Accordion.php(158): do_shortcode('\\r\\nRund um das <...')\n#4 websource/wp-includes/shortcodes.php(355): RRZE\\Elements\\Accordion\\Accordion->shortcodeCollapse(Array, '\\r\\nRund um das <...', 'collapse')\n#5 [internal function]: do_shortcode_tag(Array)\n#6 websource/wp-includes/shortcodes.php(227): preg_replace_callback('/\\\\[(\\\\[?)(captio...', 'do_shortcode_ta...', '\\r\\n<h3>Veranstal...')\n#7 websource/wp-content/plugins/rrze-elements/includes/Accordion/Accordion.php(89): do_shortcode('\\r\\n<h3>Veranstal...')\n#8 websource/wp-includes/shortcodes.php(355): RRZE\\Elements\\Accordion\\Accordion->shortcodeCollapsibles('', '\\r\\n<h3>Veranstal...', 'collapsibles')\n#9 [internal function]: do_shortcode_tag(Array)\n#10 websource/wp-includes/shortcodes.php(227): preg_replace_callback('/\\\\[(\\\\[?)(captio...', 'do_shortcode_ta...', '[caption id="at...')\n#11 websource/wp-includes/class-wp-hook.php(308): do_shortcode('[caption id="at...')\n#12 websource/wp-includes/plugin.php(205): WP_Hook->apply_filters('[caption id="at...', Array)\n#13 websource/wp-includes/post-template.php(255): apply_filters('the_content', '[caption id="at...')\n#14 page.php(39): the_content()\n#15 websource/wp-includes/template-loader.php(106): include('/proj/websource...')\n#16 websource/wp-blog-header.php(19): require_once('/proj/websource...')\n#17 websource/index.php(17): require('/proj/websource...')\n#18 {main}\n thrown in functions/shortcodes.php on line 353
```

**Comment by xwolfde** [comment]
Dub zu #1348

**Comment by xwolfde** [comment]
Danke für den Patch
